spring.application.name=conduit
spring.datasource.url=jdbc:postgresql://localhost:5432/conduit
spring.datasource.username=postgres
spring.datasource.password=aryan1010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

resilience4j.circuitbreaker.instances.taskExecution.slidingWindowSize=5
resilience4j.circuitbreaker.instances.taskExecution.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.taskExecution.failureRateThreshold=50
resilience4j.circuitbreaker.instances.taskExecution.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.taskExecution.permittedNumberOfCallsInHalfOpenState=2