spring.application.name=conduit
spring.datasource.url=jdbc:postgresql://localhost:5432/conduit
spring.datasource.username=postgres
spring.datasource.password=aryan1010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080