spring.application.name=conduit
spring.datasource.url=jdbc:postgresql://localhost:5432/conduit
spring.datasource.username=postgres
spring.datasource.password=aryan1010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
management.prometheus.metrics.export.enabled=true

resilience4j.circuitbreaker.instances.taskExecution.slidingWindowSize=5
resilience4j.circuitbreaker.instances.taskExecution.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.taskExecution.failureRateThreshold=50
resilience4j.circuitbreaker.instances.taskExecution.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.taskExecution.permittedNumberOfCallsInHalfOpenState=2
spring.data.redis.host=localhost
spring.data.redis.port=6379
conduit.worker.recovery.idle-timeout-ms=30000
conduit.worker.recovery.batch-size=10

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=conduit-workflow-triggers
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.aryan.conduit.trigger
spring.kafka.consumer.properties.spring.json.value.default.type=com.aryan.conduit.trigger.WorkflowTriggerEvent
